Main/urls.py
from django.urls import path

from . import views

app_name = "Main"

urlpatterns = [
    path("", views.inicio, name="inicio"),
]

ProyectoTienda/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("Main.urls")),
    path("catalogo/", include("mymusicstore.urls")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mymusicstore/urls.py
from django.urls import path

from . import views
from .views import CatalogoListView, DiscoDetailView, RegistrarDiscoCreateView, RegistrarDiscoDestacadoCreateView, DiscoDestacadoDetailView, DiscoUpdateView, DiscoDeleteView

app_name = "mymusicstore"

urlpatterns = [
    path("", CatalogoListView.as_view(), name="catalogo"),
    path("registrardisco", RegistrarDiscoCreateView.as_view(), name="registrardisco"),
    path("registrardiscodestacado", RegistrarDiscoDestacadoCreateView.as_view(), name="registrardiscodestacado"),
    path("detalle/<int:pk>/", DiscoDetailView.as_view(), name="detalle_disco"),
    path("detalle_destacado/<int:pk>/", DiscoDestacadoDetailView.as_view(), name="detalle_disco_destacado"),
    path("editar/<int:pk>/", DiscoUpdateView.as_view(), name="editar_disco"),
    path("eliminar/<int:pk>/", DiscoDeleteView.as_view(), name="eliminar_disco"),
    path("registrarusuario", views.registrarusuario, name="registrarusuario"),
    path("contacto", views.contacto, name="contacto"),
    path('perfil/<int:usuario_id>/', views.perfil_usuario, name='perfil_usuario'),
    path('iniciarsesion/', views.iniciarsesion, name='iniciarsesion'),
    path('cerrarsesion/', views.cerrarsesion, name='cerrarsesion'),
    path('perfil/<int:usuario_id>/editar/', views.editar_perfil, name='editar_perfil'),
]

mymusicstore/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField

# Create your models here.
class Disco(models.Model):
    class Estado(models.TextChoices):
        BORRADOR = 'B', 'Borrador'
        PUBLICADO = 'P', 'Publicado'
    nombre = models.CharField(max_length=100)
    precio = models.IntegerField()
    descripcion = RichTextField()
    imagen = models.ImageField(upload_to='discos/', null=True, blank=True)
    fecha_publicacion = models.DateField(auto_now_add=True)
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    estado = models.CharField(max_length=1, choices=Estado.choices, default=Estado.BORRADOR)

    def __str__(self):
        return self.nombre
    
class DiscoDestacado(models.Model):
    class Estado(models.TextChoices):
        BORRADOR = 'B', 'Borrador'
        PUBLICADO = 'P', 'Publicado'
    nombre = models.CharField(max_length=50)
    precio = models.IntegerField()
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    descripcion = models.TextField()
    imagen = models.ImageField(upload_to='discosdestacados/', null=True, blank=True)
    estado = models.CharField(max_length=1, choices=Estado.choices, default=Estado.BORRADOR)

    def __str__(self):
        return self.nombre
    
class RegistrarUsuario(models.Model):
    class Estado(models.TextChoices):
        ACTIVO = 'A', 'Activo'
        INACTIVO = 'I', 'Inactivo'
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    email = models.EmailField(unique=True)
    contrasena = models.CharField(max_length=50)
    telefono = models.IntegerField()
    direccion = models.CharField(max_length=100)
    estado = models.CharField(max_length=1, choices=Estado.choices, default=Estado.ACTIVO)
    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True)
    biografia = models.TextField(null=True, blank=True)
    fecha_de_cumpleanios = models.DateField(null=True, blank=True)

    def __str__(self):
        return f"{self.nombre} {self.apellido}"
    
class Contacto(models.Model):
    nombre = models.CharField(max_length=100)
    profesion = models.CharField(max_length=100)
    ubicacion = models.CharField(max_length=100)
    linkedin = models.URLField()
    behance = models.URLField()
    instagram = models.URLField()
    discord = models.CharField(max_length=100)
    imagen = models.ImageField(upload_to='contacto/', null=True, blank=True)

    def __str__(self):
        return self.nombre

mymusicstore/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import EmailValidator
import re
from .models import RegistrarUsuario, Disco, DiscoDestacado, Contacto

class UsuarioForm(forms.ModelForm):
    email = forms.EmailField(
        validators=[EmailValidator(message="Ingrese un email válido con '@' y '.com'")],
        required=True,
        error_messages={'required': 'Este campo es obligatorio'}
    )

    class Meta:
        model = RegistrarUsuario
        fields = ['nombre', 'apellido', 'email', 'contrasena', 'telefono', 'direccion']
        widgets = {
            'contrasena': forms.PasswordInput(),
        }
        error_messages = {
            'nombre': {'required': 'Este campo es obligatorio'},
            'apellido': {'required': 'Este campo es obligatorio'},
            'telefono': {'required': 'Este campo es obligatorio'},
            'direccion': {'required': 'Este campo es obligatorio'},
        }

    def clean_telefono(self):
        telefono = self.cleaned_data.get('telefono')
        telefono_str = str(telefono)
        if not re.fullmatch(r'\d{9}', telefono_str):
            raise ValidationError('El teléfono debe tener exactamente 9 dígitos.')
        return telefono

    def clean_contrasena(self):
        contrasena = self.cleaned_data.get('contrasena')
        if len(contrasena) < 8:
            raise ValidationError('La contraseña debe tener al menos 8 caracteres.')
        return contrasena

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if '@' not in email or not email.endswith('.com'):
            raise ValidationError("Ingrese un email válido con '@' y '.com'")
        if RegistrarUsuario.objects.filter(email=email).exists():
            raise ValidationError("Este email ya está en uso.")
        return email

class DiscoForm(forms.ModelForm):
    class Meta:
        model = Disco
        fields = ['nombre', 'precio', 'descripcion', 'imagen', 'estado']

    def clean_nombre(self):
        nombre = self.cleaned_data.get('nombre')
        if not nombre:
            raise forms.ValidationError("El nombre es obligatorio.")
        return nombre

    def clean_precio(self):
        precio = self.cleaned_data.get('precio')
        if precio is None or precio <= 0:
            raise forms.ValidationError("El precio debe ser mayor que cero.")
        return precio
    
class DiscoDestacadoForm(forms.ModelForm):
    disco_id = forms.ChoiceField(
        choices=[],
        label="Seleccionar Disco",
        widget=forms.Select(attrs={'class': 'form-control'})
    )

    class Meta:
        model = DiscoDestacado
        fields = ["disco_id", "estado"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['disco_id'].choices = [(disco.id, f"{disco.nombre} - S/{disco.precio}") for disco in Disco.objects.all()]

    def clean_disco_id(self):
        disco_id = self.cleaned_data.get('disco_id')
        if not disco_id:
            raise forms.ValidationError("Debe seleccionar un disco.")
        return disco_id

class EditarPerfilForm(forms.ModelForm):
    fecha_de_cumpleanios = forms.DateField(
        widget=forms.DateInput(format='%d/%m/%Y', attrs={'placeholder': 'DD/MM/YYYY'}),
        input_formats=['%d/%m/%Y']
    )

    class Meta:
        model = RegistrarUsuario
        fields = ['nombre', 'apellido', 'email', 'telefono', 'direccion', 'biografia', 'fecha_de_cumpleanios', 'avatar']

class CambiarContrasenaForm(forms.Form):
    nueva_contrasena = forms.CharField(widget=forms.PasswordInput(), required=False)
    confirmar_contrasena = forms.CharField(widget=forms.PasswordInput(), required=False)

    def clean(self):
        cleaned_data = super().clean()
        nueva_contrasena = cleaned_data.get('nueva_contrasena')
        confirmar_contrasena = cleaned_data.get('confirmar_contrasena')

        if nueva_contrasena and nueva_contrasena != confirmar_contrasena:
            raise forms.ValidationError('Las contraseñas no coinciden.')
        return cleaned_data
    
class ContactoForm(forms.ModelForm):
    class Meta:
        model = Contacto
        fields = ['nombre', 'profesion', 'ubicacion', 'linkedin', 'behance', 'instagram', 'discord', 'imagen']

mymusicstore/templates/mymusicstore/catalogo.html
{% extends 'Main/base.html' %}

{% block title %}
    Inicio
{% endblock title %}

{% block content_title %}
    <b> Vinilos </b>
{% endblock content_title %}

{% block content_title_actions %}
    <a href="{% url 'mymusicstore:registrardisco' %}" class="btn btn-primary">Agregar Disco</a>
{% endblock content_title_actions %}

{% block content %}
    <div class="row">
        {% for disco in discos %}
            <div class="col-12 col-sm-6 col-md-4 col-lg-3 mb-3">
                <div class="card h-100">
                    <div class="card h-100" style="background-color: #f8f9fa;">
                        {% if disco.imagen %}
                            <img src="{{ disco.imagen.url }}" class="card-img-top" alt="{{ disco.nombre }}">
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{ disco.nombre }}</h5>
                            <p class="card-text">S/{{ disco.precio }}</p>
                            <a href="{% url 'mymusicstore:detalle_disco' disco.id %}" class="btn btn-primary">Ver detalles</a>
                        </div>
                    </div>
                </div>        
            </div>
        {% empty %}
            <p>No hay discos disponibles en este momento.</p>
        {% endfor %}
    </div>
{% endblock content %}


{% block footer %}
    <footer class="bg-dark text-white p-1 mt-auto">
        <div class="container">
            <p class="text-center">© 2025 Tienda de Vinilos. Todos los derechos reservados.</p>
        </div>
    </footer>
{% endblock footer %}

mymusicstore/templates/mymusicstore/contacto.html
{% extends 'Main/base.html' %}

{% load static %}

{% block title %}
    Contacto
{% endblock title %}

{% block content_title %}
    <b>Contacto</b> 
{% endblock content_title %}

{% block content %}
    <div class="col-lg-12">
        <h3>Sobre mi:</h3>
        <div class="row align-items-center">
            <div class="col-md-4 mb-4">
                {% if contacto.imagen %}
                    <div class="mt-4">
                        <img src="{{ contacto.imagen.url }}" class="img-fluid" alt="{{ contacto.nombre }}">
                    </div>
                {% endif %}
            </div>
            <div class="col-md-8">
                <p><strong>Nombre:</strong> {{ contacto.nombre }}</p>
                <p><strong>Profesión:</strong> {{ contacto.profesion }}</p>
                <p><strong>Ubicación:</strong> {{ contacto.ubicacion }}</p>
                <p><strong>LinkedIn:</strong> <a href="{{ contacto.linkedin }}" target="_blank">{{ contacto.linkedin }}</a></p>
                <p><strong>Behance:</strong> <a href="{{ contacto.behance }}" target="_blank">{{ contacto.behance }}</a></p>
                <p><strong>Instagram:</strong> <a href="{{ contacto.instagram }}" target="_blank">{{ contacto.instagram }}</a></p>
                <p><strong>Discord:</strong> {{ contacto.discord }}</p>
            </div>
        </div>
    </div>
{% endblock content %}

{% block footer %}
    <footer class="bg-dark text-white p-1 mt-auto">
        <div class="container">
            <p class="text-center">© 2025 Tienda de Vinilos. Todos los derechos reservados.</p>
        </div>
    </footer>
{% endblock footer %}

mymusicstore/templates/mymusicstore/detalle_disco.html
{% extends 'Main/base.html' %}

{% block title %}
    Detalle del Disco
{% endblock title %}

{% block content_title %}
    {{ disco.nombre }}
{% endblock content_title %}

{% block content %}
    <div class="container my-4">
        <div class="row">
            <div class="col-md-4">
                {% if disco.imagen %}
                    <div class="mt-4">
                        <img src="{{ disco.imagen.url }}" class="img-fluid" alt="{{ disco.nombre }}">
                    </div>
                {% endif %}
            </div>
            <div class="col-md-8">
                <p><strong>Precio:</strong> S/{{ disco.precio }}</p>
                <p><strong>Descripción:</strong> {{ disco.descripcion }}</p>
                <p><strong>Fecha de Publicación:</strong> {{ disco.fecha_publicacion }}</p>
                <a href="{% url 'mymusicstore:editar_disco' disco.id %}" class="btn btn-warning">Editar</a>
                <a href="{% url 'mymusicstore:eliminar_disco' disco.id %}" class="btn btn-danger">Eliminar</a>
            </div>
        </div>
    </div>
{% endblock content %}

{% block footer %}
    <footer class="bg-dark text-white p-1 mt-auto">
        <div class="container">
            <p class="text-center">© 2025 Tienda de Vinilos. Todos los derechos reservados.</p>
        </div>
    </footer>
{% endblock footer %}

mymusicstore/templates/mymusicstore/detalle_disco_destacado.html
{% extends 'Main/base.html' %}

{% block title %}
    Detalle del Disco Destacado
{% endblock title %}

{% block content_title %}
    {{ discodestacado.nombre }}
{% endblock content_title %}

{% block content %}
    <div class="container my-4">
        <div class="row">
            <div class="col-md-4">
                {% if discodestacado.imagen %}
                    <div class="mt-4">
                        <img src="{{ discodestacado.imagen.url }}" class="img-fluid" alt="{{ discodestacado.nombre }}">
                    </div>
                {% endif %}
            </div>
            <div class="col-md-8">
                <p><strong>Precio:</strong> S/{{ discodestacado.precio }}</p>
                <p><strong>Descripción:</strong> {{ discodestacado.descripcion }}</p>
            </div>
        </div>
    </div>
{% endblock content %}

{% block footer %}
    <footer class="bg-dark text-white p-1 mt-auto">
        <div class="container">
            <p class="text-center">© 2025 Tienda de Vinilos. Todos los derechos reservados.</p>
        </div>
    </footer>
{% endblock footer %}

mymusicstore/templates/mymusicstore/editar_disco.html
{% extends 'Main/base.html' %}

{% block title %}
    Editar Disco
{% endblock title %}

{% block content_title %}
    Editar Disco
{% endblock content_title %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Guardar Cambios</button>
    </form>
{% endblock content %}

{% block footer %}
    <footer class="bg-dark text-white p-1 mt-auto">
        <div class="container">
            <p class="text-center">© 2025 Tienda de Vinilos. Todos los derechos reservados.</p>
        </div>
    </footer>
{% endblock footer %}

mymusicstore/templates/mymusicstore/editar_perfil.html
{% extends 'Main/base.html' %}

{% block title %}
    Editar Perfil
{% endblock title %}

{% block content_title %}
    <b>Editar Perfil de {{ form.instance.nombre }} {{ form.instance.apellido }}</b>
{% endblock content_title %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group mb-4">
            <label for="id_nombre"><b>Nombre:</b></label>
            {{ form.nombre }}
        </div>
        <div class="form-group mb-4">
            <label for="id_apellido"><b>Apellido:</b></label>
            {{ form.apellido }}
        </div>
        <div class="form-group mb-4">
            <label for="id_email"><b>Email:</b></label>
            {{ form.email }}
        </div>
        <div class="form-group mb-4">
            <label for="id_telefono"><b>Teléfono:</b></label>
            {{ form.telefono }}
        </div>
        <div class="form-group mb-4">
            <label for="id_direccion"><b>Dirección:</b></label>
            {{ form.direccion }}
        </div>
        <div class="form-group mb-4">
            <label for="id_biografia"><b>Biografía:</b></label>
            {{ form.biografia }}
        </div>
        <div class="form-group mb-4">
            <label for="id_fecha_de_cumpleanios"><b>Fecha de Cumpleaños:</b></label>
            {{ form.fecha_de_cumpleanios }}
        </div>
        <div class="form-group mb-4">
            <label for="id_avatar"><b>Avatar:</b></label>
            {{ form.avatar }}
            </div>
        <h3>Cambiar Contraseña</h3>
        <div class="form-group mb-4">
            <label for="id_nueva_contrasena"><b>Nueva Contraseña:</b></label>
            {{ password_form.nueva_contrasena }}
        </div>
        <div class="form-group mb-4">
            <label for="id_confirmar_contrasena"><b>Confirmar Contraseña:</b></label>
            {{ password_form.confirmar_contrasena }}
        </div>
        <button type="submit" class="btn btn-primary">Guardar Cambios</button>
        <a href="{% url 'mymusicstore:perfil_usuario' form.instance.id %}" class="btn btn-secondary">Cancelar</a>
    </form>
{% endblock content %}

{% block footer %}
    <footer class="bg-dark text-white p-1 mt-auto">
        <div class="container">
            <p class="text-center">© 2025 Tienda de Vinilos. Todos los derechos reservados.</p>
        </div>
    </footer>
{% endblock footer %}

mymusicstore/templates/mymusicstore/eliminar_disco.html
{% extends 'Main/base.html' %}

{% block title %}
    Eliminar Disco
{% endblock title %}

{% block content_title %}
    Eliminar Disco
{% endblock content_title %}

{% block content %}
    <p>¿Estás seguro de que deseas eliminar el disco "{{ object.nombre }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Eliminar</button>
        <a href="{% url 'mymusicstore:catalogo' %}" class="btn btn-secondary">Cancelar</a>
    </form>
{% endblock content %}

{% block footer %}
    <footer class="bg-dark text-white p-1 mt-auto">
        <div class="container">
            <p class="text-center">© 2025 Tienda de Vinilos. Todos los derechos reservados.</p>
        </div>
    </footer>
{% endblock footer %}

mymusicstore/templates/mymusicstore/iniciarsesion.html
{% extends 'Main/base.html' %}

{% block title %}
    Iniciar Sesion
{% endblock title %}

{% block content_title %}
    <b>Iniciar Sesion</b>
{% endblock content_title %}

{% block content %}
    <div class="container mt-5">
        {% if messages %}
            <div class="alert alert-danger">
                {% for message in messages %}
                    <p>{{ message }}</p>
                {% endfor %}
            </div>
        {% endif %}

        <form method="POST">
            {% csrf_token %}
            <div class="mb-4">
                <label for="email" class="form-label"> <b>Correo Electrónico</b></label>
                <input type="email" name="email" class="form-control" id="email" required>
            </div>
            <div class="mb-4">
                <label for="contrasena" class="form-label"> <b>Contraseña</b></label>
                <input type="password" name="contrasena" class="form-control" id="contrasena" required>
            </div>
            <button type="submit" class="btn btn-primary">Iniciar Sesión</button>
        </form>
    </div>
{% endblock content %}

{% block footer %}
    <footer class="bg-dark text-white p-1 mt-auto">
        <div class="container">
            <p class="text-center">© 2025 Tienda de Vinilos. Todos los derechos reservados.</p>
        </div>
    </footer>
{% endblock footer %}

mymusicstore/templates/mymusicstore/perfil_usuario.html
{% extends 'Main/base.html' %}

{% block title %}
    Perfil de Usuario
{% endblock title %}

{% block content_title %}
    <b> Perfil de {{ usuario.nombre }} {{ usuario.apellido }}</b>
{% endblock content_title %}

{% block content %}
    <div class="col-lg-12">
        <div class="row align-items-center">
            <div class="col-md-4">
                {% if usuario.avatar %}
                    <div class="mt-4 mb-4">
                        <img src="{{ usuario.avatar.url }}" class="img-fluid" alt="Avatar de {{ usuario.nombre }}">
                    </div>
                {% endif %}
            </div>
            <div class="col-md-8">
                <p><strong>Email:</strong> {{ usuario.email }}</p>
                <p><strong>Teléfono:</strong> {{ usuario.telefono }}</p>
                <p><strong>Dirección:</strong> {{ usuario.direccion }}</p>
                <p><strong>Estado:</strong> {{ usuario.get_estado_display }}</p>
                <p><strong>Biografía:</strong> {{ usuario.biografia }}</p>
                <p><strong>Fecha de cumpleaños:</strong> {{ usuario.fecha_de_cumpleanios }}</p>
                <a href="{% url 'mymusicstore:editar_perfil' usuario.id %}" class="btn btn-primary">Editar Perfil</a>
            </div>
        </div>
    </div>
{% endblock content %}

{% block footer %}
    <footer class="bg-dark text-white p-1 mt-auto">
        <div class="container">
            <p class="text-center">© 2025 Tienda de Vinilos. Todos los derechos reservados.</p>
        </div>
    </footer>
{% endblock footer %}

mymusicstore/templates/mymusicstore/registrardisco.html
{% extends 'Main/base.html' %}

{% block title %}
    Registrar Disco
{% endblock title %}

{% block content_title %}
    <b>Registrar Disco Nuevo</b>
{% endblock content_title %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group mb-4">
            <label for="id_nombre"><b>Nombre:</b></label>
            {{ form.nombre }}
        </div>
        <div class="form-group mb-4">
            <label for="id_precio"><b>Precio:</b></label>
            {{ form.precio }}
        </div>
        <div class="form-group mb-4">
            <label for="id_descripcion"><b>Descripción:</b></label>
            {{ form.descripcion }}
        </div>
        <div class="form-group mb-4">
            <label for="id_imagen"><b>Imagen:</b></label>
            {{ form.imagen }}
        </div>
        <div class="form-group mb-4">
            <label for="id_estado"><b>Estado:</b></label>
            {{ form.estado }}
        </div>
        {% if form.errors %}
            <div class="alert alert-danger">
                <ul>
                    {% for field in form %}
                        {% for error in field.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
        <button type="submit" class="btn btn-primary">Registrar Disco</button>
    </form>
{% endblock content %}

{% block footer %}
    <footer class="bg-dark text-white p-1 mt-auto">
        <div class="container">
            <p class="text-center">© 2025 Tienda de Vinilos. Todos los derechos reservados.</p>
        </div>
    </footer>
{% endblock footer %}

mymusicstore/templates/mymusicstore/registrardiscodestacado.html
{% extends 'Main/base.html' %}

{% block title %}
    Elegir Disco
{% endblock title %}

{% block content_title %}
   <b>Elegir Disco Destacado</b>
{% endblock content_title %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <div class="form-group mb-4">
            <label for="disco_id"> <b>Seleccionar Disco</b></label>
            <select id="disco_id" name="disco_id" class="form-control">
                {% for disco in discos %}
                    <option value="{{ disco.id }}">{{ disco.nombre }} - S/{{ disco.precio }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group mb-4">
            <label for="estado"><b>Estado</b></label>
            <select id="estado" name="estado" class="form-control">
                <option value="B">Borrador</option>
                <option value="P">Publicado</option>
            </select>
        </div>
        <button type="submit" class="btn btn-primary mb-3">Registrar Disco Destacado</button>
    </form>
{% endblock content %}

{% block footer %}
    <footer class="bg-dark text-white p-1 mt-auto">
        <div class="container">
            <p class="text-center">© 2025 Tienda de Vinilos. Todos los derechos reservados.</p>
        </div>
    </footer>
{% endblock footer %}

mymusicstore/templates/mymusicstore/registrarusuario.html
{% extends 'Main/base.html' %}

{% block title %}
    Registrarse
{% endblock title %}

{% block content_title %}
    <b>Registrar Usuario</b>
{% endblock content_title %}

{% block content %}
    {% load widget_tweaks %}
    <form action="" method="post">
        {% csrf_token %}
        
        <div class="form-group mb-4">
            <label for="{{ form.nombre.id_for_label }}"><b>Nombre</b></label>
            {{ form.nombre|add_class:"form-control mb-2" }}
            {% if form.nombre.errors %}
                <div class="invalid-feedback">
                    {% for error in form.nombre.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        
        <div class="form-group mb-4">
            <label for="{{ form.apellido.id_for_label }}"><b>Apellido</b></label>
            {{ form.apellido|add_class:"form-control mb-2" }}
            {% if form.apellido.errors %}
                <div class="invalid-feedback">
                    {% for error in form.apellido.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        
        <div class="form-group mb-4">
            <label for="{{ form.email.id_for_label }}"><b>Email</b></label>
            {{ form.email|add_class:"form-control mb-2" }}
            {% if form.email.errors %}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        
        <div class="form-group mb-4">
            <label for="{{ form.telefono.id_for_label }}"><b>Teléfono</b></label>
            {{ form.telefono|add_class:"form-control mb-2" }}
            {% if form.telefono.errors %}
                <div class="invalid-feedback">
                    {% for error in form.telefono.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        
        <div class="form-group mb-4">
            <label for="{{ form.direccion.id_for_label }}"><b>Dirección</b></label>
            {{ form.direccion|add_class:"form-control mb-2" }}
            {% if form.direccion.errors %}
                <div class="invalid-feedback">
                    {% for error in form.direccion.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        
        <div class="form-group mb-4">
            <label for="{{ form.contrasena.id_for_label }}"><b>Contraseña</b></label>
            {{ form.contrasena|add_class:"form-control mb-2" }}
            {% if form.contrasena.errors %}
                <div class="invalid-feedback">
                    {% for error in form.contrasena.errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </div>

        <button type="submit" class="btn btn-primary mb-2">Registrar</button>
        <a href="{% url 'Main:inicio' %}" class="btn btn-secondary mb-2">Cancelar</a>
    </form>
{% endblock content %}

{% block footer %}
    <footer class="bg-dark text-white p-1 mt-auto">
        <div class="container">
            <p class="text-center">© 2025 Tienda de Vinilos. Todos los derechos reservados.</p>
        </div>
    </footer>
{% endblock footer %}