Main/urls.py
from django.urls import path

from . import views

app_name = "Main"

urlpatterns = [
    path("", views.inicio, name="inicio"),
]

ProyectoTienda/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("Main.urls")),
    path("catalogo/", include("mymusicstore.urls")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mymusicstore/urls.py
from django.urls import path

from . import views
from .views import CatalogoListView, DiscoDetailView, RegistrarDiscoCreateView, RegistrarDiscoDestacadoCreateView, DiscoDestacadoDetailView, DiscoUpdateView, DiscoDeleteView

app_name = "mymusicstore"

urlpatterns = [
    path("", CatalogoListView.as_view(), name="catalogo"),
    path("registrardisco", RegistrarDiscoCreateView.as_view(), name="registrardisco"),
    path("registrardiscodestacado", RegistrarDiscoDestacadoCreateView.as_view(), name="registrardiscodestacado"),
    path("detalle/<int:pk>/", DiscoDetailView.as_view(), name="detalle_disco"),
    path("detalle_destacado/<int:pk>/", DiscoDestacadoDetailView.as_view(), name="detalle_disco_destacado"),
    path("editar/<int:pk>/", DiscoUpdateView.as_view(), name="editar_disco"),
    path("eliminar/<int:pk>/", DiscoDeleteView.as_view(), name="eliminar_disco"),
    path("registrarusuario", views.registrarusuario, name="registrarusuario"),
    path("contacto", views.contacto, name="contacto"),
    path('perfil/<int:usuario_id>/', views.perfil_usuario, name='perfil_usuario'),
    path('iniciarsesion/', views.iniciarsesion, name='iniciarsesion'),
    path('cerrarsesion/', views.cerrarsesion, name='cerrarsesion'),
    path('perfil/<int:usuario_id>/editar/', views.editar_perfil, name='editar_perfil'),
]

Main/views.py
from django.shortcuts import render
from mymusicstore.models import Disco, DiscoDestacado

# Create your views here.
def inicio(request):
    disco_list = Disco.objects.all()
    discoDestacado_list = DiscoDestacado.objects.all()
    
    context = {
        "message": "Encuentra los mejores discos de vinilo para tu coleccion",
        "discos": disco_list,
        "discosdestacados": discoDestacado_list,
    }
    return render(request, "Main/inicio.html", context)

Main/templates/Main/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Buscador de Vinilos | {% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <header class="bg-dark text-white p-3">
        <div class="container">
            <h1 class="display-4"> <b> Buscador de Vinilos</b> </h1>
            <p class="lead">{{message}}</p>
        </div>
    </header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'Main:inicio' %}">Inicio</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item"><a class="nav-link" href="{% url 'mymusicstore:catalogo' %}">Catálogo</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'mymusicstore:contacto' %}">Acerca de mi</a></li>
                    {% if request.session.usuario_id %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'mymusicstore:perfil_usuario' request.session.usuario_id %}">{{ request.session.usuario_nombre }}</a>
                    </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'mymusicstore:cerrarsesion' %}">Cerrar Sesión</a>
                        </li>
                    {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'mymusicstore:iniciarsesion' %}">Iniciar Sesión</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'mymusicstore:registrarusuario'%}">Registrarse</a></li>
                        
                    {% endif %}
                </ul>
                <div class="d-flex">                
                    <form class="d-flex" action="{% url 'mymusicstore:catalogo' %}" method="GET">
                        <input class="form-control me-2" type="text" name="busqueda" placeholder="Buscar vinilo...">
                        <button class="btn btn-outline-light" type="submit">Buscar</button>
                    </form>
                </div>
            </div>
        </div>
    </nav>
    <main class="container mt-3 mb-3">
        <section>
            <h2 class="display-6 mb-3 d-flex justify-content-between align-items-center">{% block content_secondtitle %}{% endblock content_secondtitle %}</h2>
            {% block main %}        
            {% endblock main %}
        </section>
        <section>
            <h2 class="display-6 mb-3 d-flex justify-content-between align-items-center">{% block content_title %} {% endblock content_title %}</h2>
            {% block content %}        
            {% endblock content %}
        </section>
    </main>

    {% block footer %}
    {% endblock footer%}
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

Main/templates/Main/inicio.html
{% extends 'Main/base.html' %}

{% block content_secondtitle %}
    <b>Vinilos Destacados</b>
    <a href="{% url 'mymusicstore:registrardiscodestacado' %}" class="btn btn-secondary">Agregar Disco Destacado</a>
{% endblock content_secondtitle %}

{% block main %}
    <section>
        <div class="row">
            {% for discodestacado in discosdestacados %}
                <div class="col-12 col-sm-6 col-md-4 col-lg-3 mb-3">
                    <div class="card h-100" style="background-color: #f8f9fa;">
                        {% if discodestacado.imagen %}
                            <img src="{{ discodestacado.imagen.url }}" class="card-img-top" alt="{{ discodestacado.nombre }}">
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{ discodestacado.nombre }}</h5>
                            <p class="card-text">S/{{ discodestacado.precio }}</p>
                            <a href="{% url 'mymusicstore:detalle_disco_destacado' discodestacado.id %}" class="btn btn-primary">Ver detalles</a>
                        </div>
                    </div>        
                </div>
            {% empty %}
                <p>No hay discos destacados en este momento.</p>
            {% endfor %}
        </div>
    </section>
{% endblock main %}

{% block content_title %}
    <b>Vinilos más recientes</b>
    <a href="{% url 'mymusicstore:registrardisco' %}" class="btn btn-secondary">Agregar Disco</a>
{% endblock content_title %}

{% block content %}
    <div class="row">
        {% for disco in discos %}
            <div class="col-12 col-sm-6 col-md-4 col-lg-3 mb-3">
                <div class="card h-100" style="background-color: #f8f9fa;">
                    {% if disco.imagen %}
                        <img src="{{ disco.imagen.url }}" class="card-img-top" alt="{{ disco.nombre }}">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">{{ disco.nombre }}</h5>
                        <p class="card-text">S/{{ disco.precio }}</p>
                        <a href="{% url 'mymusicstore:detalle_disco' disco.id %}" class="btn btn-primary">Ver detalles</a>
                    </div>
                </div>        
            </div>
        {% empty %}
            <p>No hay discos disponibles en este momento.</p>
        {% endfor %}
    </div>
{% endblock content %}

{% block footer %}
    <footer class="bg-dark text-white p-1 mt-auto">
        <div class="container">
            <p class="text-center">© 2025 Tienda de Vinilos. Todos los derechos reservados.</p>
        </div>
    </footer>
{% endblock footer %}